Refactor copier-tasks and copier.yml

diff --git a/copier.yml b/copier.yml
--- a/copier.yml
+++ b/copier.yml
@@ -71,4 +71,29 @@ license_name:
     "No license": None
   help: License name
 _tasks:
-  - "{{ _copier_conf.src_path }}/copier-tasks"
+  - |-
+    echo "Checking if this directory is a git repository..."
+    git rev-parse --is-inside-work-tree
+    if [ $? -ne 0 ]; then  # $OPERATION=copy
+        git init .
+        poetry install
+        if [ $? -eq 0 ]; then
+            echo "Successfully installed dependencies."
+        else
+            echo "Failed to install dependencies."
+            exit 1
+        fi
+        PYTHON_VERSION="$(cat .python-version)"
+        poetry env use $PYTHON_VERSION
+        poetry run poe lock
+        poetry run python _after_copy.py
+        rm _after_copy.py
+        git add .
+        git commit -m "Initial commit"
+        gh repo create {{ repo_name }} --{{ visibility }} --source=./ --remote=upstream
+        git remote add origin https://github.com/{{ github_username }}/{{ repo_name }}.git
+        git push -u origin master
+        poetry run pre-commit install --hook-type pre-commit --hook-type pre-push
+    else  # $OPERATION=update
+        echo "This directory is a git repository."
+    fi
