Refine the UX

diff --git a/handle-task-event b/handle-task-event
--- a/handle-task-event
+++ b/handle-task-event
@@ -10,17 +10,20 @@
 # Later on, this script will be included in your project and run automatically within:
 # $ poe skeleton upgrade
 
-# shellcheck shell=sh
+# shellcheck shell=bash
 # shellcheck disable=SC1054,SC1073,SC2005,SC1083
+
+set -eEuo pipefail
 
 setup_task_event() {
     # By default use PPID not to overlap with other running copier processes
     export SKELETON_COMMAND
-    echo "[Setting up task event]"
-    echo "--- Skeleton command: ${SKELETON_COMMAND:="copy"}"
-    echo "--- Project path key: ${PROJECT_PATH_KEY:="${PPID}_skeleton_project_path"}"
+    note "(Setting up task event)"
+    info "${GREY}Skeleton command$NC: ${SKELETON_COMMAND:="copy"}"
+    info "${GREY}Project path key$NC: ${PROJECT_PATH_KEY:="${PPID}_skeleton_project_path"}"
 
     # It is a temporary directory that copier uses before or after updating
+    set +eE
     if test "$(pwd | grep "^/tmp/")"
     then
         # Before update
@@ -33,15 +36,15 @@ setup_task_event() {
         fi
     else
         # Export the project path to parent process
-        redis-cli set "$PROJECT_PATH_KEY" "$(pwd)" > /dev/null 2>&1
+        silent redis-cli set "$PROJECT_PATH_KEY" "$(pwd)"
 
         # Does this repository exist remotely?
-        git ls-remote "{{repo_url}}" HEAD > /dev/null 2>&1
-
+        silent git ls-remote "{{repo_url}}" HEAD
         if test $? = 0 && test "$LAST_REF"  # Missing $LAST_REF means we are not updating.
         then
             # Let the parent process know what is the new skeleton revision
-            redis-cli set "$NEW_REF_KEY" "{{sref}}"
+            set -eE
+            silent redis-cli set "$NEW_REF_KEY" "{{sref}}"
             export TASK_EVENT="UPGRADE"
             export BRANCH
             BRANCH="$(git rev-parse --abbrev-ref HEAD)"
@@ -50,33 +53,34 @@ setup_task_event() {
             export TASK_EVENT="COPY"
         fi
     fi
+    set -eE
 
     determine_project_path
-    echo "--- Task stage: $TASK_EVENT"
-    echo "--- Last skeleton revision: ${LAST_REF:-"N/A"}"
-    echo "--- Project path: ${PROJECT_PATH:-"N/A"}"
-    echo "--- Runner ID: $PPID"
+    info "${GREY}Task stage$NC: $TASK_EVENT"
+    info "${GREY}Last skeleton revision$NC: ${LAST_REF:-"N/A"}"
+    info "${GREY}Project path$NC: ${PROJECT_PATH:-"N/A"}"
+    info "${GREY}Runner ID$NC: $PPID"
     echo
 }
 
 run_copier_hook() {
     # Run a temporary hook that might generate LICENSE file and other stuff
-    echo "Running copier hook..."
+    note "Running copier hook..."
     python copier_hook.py
-    echo "Copier hook exited with code $?."
-    echo "Removing copier hook..."
-    rm copier_hook.py || (echo "Failed to remove copier hook." 1>&2 && exit 1)
+    info "Copier hook exited with code $BOLD$?$NC."
+    note "Removing copier hook..."
+    rm copier_hook.py || (error $? "Failed to remove copier hook.")
 }
 
 setup_poetry_virtualenv() {
     # Set up poetry virtualenv. This is needed for copier to work flawlessly.
     #% if not ctt_mode %#
-    echo "Using Python version ${PYTHON_VERSION:=$(cat .python-version)}"
+    note "Using Python version ${PYTHON_VERSION:=$(cat .python-version)}"
     poetry env use "$PYTHON_VERSION"
-    echo "Running poetry installation for the $TASK_EVENT routine..."
+    note "Running poetry installation for the $TASK_EVENT routine..."
     if test "$TASK_EVENT" = "COPY"
     then
-        poetry update || (echo "Failed to install dependencies." 1>&2 && exit 1)
+        poetry update || (error $? "Failed to install dependencies.")
     fi
     poetry lock --no-update
     #% else %#
@@ -86,7 +90,7 @@ setup_poetry_virtualenv() {
 
 after_copy() {
     # This is the first time the skeleton is integrated into the project.
-    echo "Setting up the project..."
+    note "Setting up the project..."
     echo
     setup_poetry_virtualenv
     run_copier_hook
@@ -95,10 +99,10 @@ after_copy() {
     if test "$(git rev-parse --show-toplevel)" != "$(pwd)"
     then
         BRANCH="main"
-        echo "Initializing git repository..."
+        note "Initializing git repository..."
         git init .
         git branch -M "$BRANCH"
-        echo "Main branch: $BRANCH"
+        info "Main branch: $BRANCH"
         gh repo create {{gh.repo_args}}
         git remote add origin "{{repo_url}}.git"
         CREATED=1
@@ -121,12 +125,12 @@ after_copy() {
         setup_gh
     else
         git revert --no-commit HEAD
-        echo "Reverted the latest commit to complete the integration process."
+        info "Reverted the latest commit to complete the integration process."
         echo "Patch your files and commit your changes with the --am option"
         echo "to inform copier what needs to be kept."
         echo
         echo "Then run:"
-        echo "$ poe skeleton upgrade"
+        echo "💲 poe skeleton upgrade"
     fi
     #% endif %#
 }
@@ -161,56 +165,84 @@ handle_task_event() {
     if test "$TASK_EVENT" = "COPY"
     then
         clear
-        echo "COPY ROUTINE: Copying the skeleton."
-        echo "-----------------------------------"
+        note "COPY ROUTINE: Copying the skeleton."
         after_copy
         determine_project_path
-        echo "-----------------------------------"
-        echo "COPY ROUTINE COMPLETE. ✅"
+        success "COPY ROUTINE COMPLETE."
         echo
         #% if not ctt_mode %#
-        echo "Done! 🎉"
-        echo "Your repository is now set up at {{repo_url}}"
-        echo "$ cd $PROJECT_PATH"
+        success "Done! 🎉"
+        info "Your repository is now set up at $BOLD{{repo_url}}$NC"
+        info "$ cd $PROJECT_PATH"
         echo
         echo "Happy coding!"
-        echo "-- bswck"
-        redis-cli del "$PROJECT_PATH_KEY" > /dev/null 2>&1
+        echo -e "$GREY-- bswck$NC"
+        silent redis-cli del "$PROJECT_PATH_KEY"
         #% endif %#
     elif test "$TASK_EVENT" = "CHECKOUT_LAST_SKELETON"
     then
-        echo "UPGRADE ALGORITHM [1/3]: Checked out the last used skeleton before update."
-        echo "--------------------------------------------------------------------------"
+        info "UPGRADE ALGORITHM [1/3]: Checked out the last used skeleton before update."
         after_checkout_last_skeleton
         before_update
-        echo "--------------------------------------------------------------------------"
-        echo "UPGRADE ALGORITHM [1/3] COMPLETE. ✅"
+        success "UPGRADE ALGORITHM [1/3] COMPLETE."
         echo
     elif test "$TASK_EVENT" = "UPGRADE"
     then
-        echo "UPGRADE ALGORITHM [2/3]: Overwrote the old skeleton before checking out the project."
-        echo "------------------------------------------------------------------------------------"
-        echo "Re-setting up the project..."
+        info "UPGRADE ALGORITHM [2/3]: Overwrote the old skeleton before checking out the project."
+        note "Re-setting up the project..."
         after_update
         before_checkout_project
-        echo "------------------------------------------------------------------------------------"
-        echo "UPGRADE ALGORITHM [2/3] COMPLETE. ✅"
+        success "UPGRADE ALGORITHM [2/3] COMPLETE."
         echo
     elif test "$TASK_EVENT" = "CHECKOUT_PROJECT"
     then
-        echo "UPGRADE ALGORITHM [3/3]: Checked out the project."
-        echo "-------------------------------------------------"
+        info "UPGRADE ALGORITHM [3/3]: Checked out the project."
         after_checkout_project
-        echo "-------------------------------------------------"
-        echo "UPGRADE ALGORITHM [3/3] COMPLETE. ✅"
+        success "UPGRADE ALGORITHM [3/3] COMPLETE."
     fi
 }
 #%- endif %#
 #%- if upgrade_script %#
 # Automatically copied from {{skeleton_url}}/tree/{{sref}}/handle-task-event.sh
 #%- endif %#
+# Comms
+BOLD="\033[1m"
+RED="\033[0;31m"
+GREEN="\033[0;32m"
+BLUE="\033[0;34m"
+GREY="\033[0;90m"
+NC="\033[0m"
+
+UI_INFO="${BLUE}🛈${NC}"
+UI_NOTE="${GREY}→${NC}"
+UI_TICK="${GREEN}✔${NC}"
+UI_CROSS="${RED}✘${NC}"
+
+info() {
+    echo -e "$UI_INFO" "$@"
+}
+
+note() {
+    echo -e "$UI_NOTE $GREY$*$NC"
+}
+
+success() {
+    echo -e "$UI_TICK" "$@"
+}
+
+silent() {
+    local CMD=$1
+    "$CMD" "${@:2}" > /dev/null 2>&1
+}
+
+error() {
+    local CODE=$1
+    echo -e "$UI_CROSS" "${@:2}" >&2
+    return "$CODE"
+}
+
 setup_gh() {
-    echo "Calling GitHub setup hooks..."
+    note "Calling GitHub setup hooks..."
     #%- if public %#
     supply_smokeshow_key
     #%- endif %#
@@ -224,27 +256,42 @@ determine_project_path() {
 
 ensure_gh_environment() {
     # Ensure that the GitHub environment exists
-    echo "{{gh.ensure_env}}" > /dev/null 2>&1 || return 1
+    silent echo "{{gh.ensure_env}}"
 }
 
-supply_smokeshow_key() {
-    # Supply smokeshow key to the repository
-    echo "Checking if smokeshow secret needs to be created..."
-    ensure_gh_environment "Smokeshow"
-    if test "$(gh secret list -e Smokeshow | grep -o SMOKESHOW_AUTH_KEY)"
+supply_keys() {
+    local SMOKESHOW_KEY
+    local CODECOV_TOKEN
+
+    info "Checking if smokeshow secret needs to be created..."
+    ensure_gh_environment "Upload Coverage"
+    if test "$(gh secret list -e "Upload Coverage" | grep -o SMOKESHOW_KEY)"
     then
-        echo "Smokeshow secret already exists, aborting." && return 0
+        info "Smokeshow secret already exists, aborting." && return 0
     fi
-    echo "Smokeshow secret does not exist, creating..."
-    SMOKESHOW_AUTH_KEY=$(smokeshow generate-key | grep SMOKESHOW_AUTH_KEY | grep -oP "='\K[^']+")
-    gh secret set SMOKESHOW_AUTH_KEY --env Smokeshow --body "$SMOKESHOW_AUTH_KEY" 2> /dev/null
+    info "Smokeshow secret does not exist, creating..."
+
+    SMOKESHOW_KEY=$(smokeshow generate-key | grep SMOKESHOW_KEY | grep -oP "='\K[^']+")
+
+    silent gh secret set SMOKESHOW_KEY --env "Upload Coverage" --body "$SMOKESHOW_KEY"
     if test $? = 0
     then
-        echo "Smokeshow secret created."
+        success "Smokeshow secret created."
     else
-        echo "Failed to create smokeshow secret." 1>&2
+        error 0 "Failed to create smokeshow secret."
+    fi
+    CODECOV_TOKEN=$(keyring get codecov token)
+    silent gh secret set CODECOV_TOKEN --env "Upload Coverage" --body "$CODECOV_TOKEN"
+    if test $? = 0
+    then
+        success "Codecov secret created."
+    else
+        error 0 "Failed to create codecov secret."
     fi
 }
 #%- if upgrade_script %#
 # End of copied code
-#%- endif -%#
+#%- endif %#
+
+setup_task_event
+handle_task_event
